# Configuration of Jekyll
source: presentation/
destination: _presentation/
exclude: []
keep_files: [contrib, css, fonts, images, js]

# Site settings
title: "Scientific Programming with C++"
institute: "Institute of Scientific Computing"
email: simon.praetorius@tu-dresden.de
description: "Lecture slides for SCPROG Scientific Programming, Advanced Aspects So2021"
author: "Dr. Simon Praetorius"
semester: "Summer term 2021"
